### ISSUE TITLE
🐛 possible duplication of read group data between different SONG payloads

### ISSUE THREAD

**Issue by junjun-zhang** [icgc-argo/argo-meta#1]
## Describe the bug
Some SONG payloads include read groups with the same **submitter_read_group_id**, this may be indication of duplicated sequencing data

## Steps To Reproduce
Same `submitter_read_group_id: 140828_D00343_0065_AC4PK5ANXX_1_NoIndex` exists in [EGAZ00001315466.json](https://github.com/icgc-argo/argo-meta/blob/a95e74ca7f4b943a2e70040e8352f5518af3765e/icgc_song_payloads/PACA-CA/EGAZ00001315466.json) and in [EGAR00001268083.json](https://github.com/icgc-argo/argo-meta/blob/a95e74ca7f4b943a2e70040e8352f5518af3765e/icgc_song_payloads/PACA-CA/EGAR00001268083.json)

Similarly: `140828_D00343_0065_AC4PK5ANXX_2_NoIndex` exists in [EGAZ00001315466.json](https://github.com/icgc-argo/argo-meta/blob/a95e74ca7f4b943a2e70040e8352f5518af3765e/icgc_song_payloads/PACA-CA/EGAZ00001315466.json) and also in [EGAR00001268081.json](https://github.com/icgc-argo/argo-meta/blob/a95e74ca7f4b943a2e70040e8352f5518af3765e/icgc_song_payloads/PACA-CA/EGAR00001268081.json)

## Expected behaviour
There shouldn't be any duplicated sequencing data between different SONG entries. If a read group is part of `EGAZ....`, `EGAR....` containing the same read group probably should be removed.

**Comment by hknahal** [comment]
After consulting with PACA-CA project, SONG payloads with duplicated read groups have been removed.
