### ISSUE TITLE
🐛 PCAWG mini-bam entries should be removed

### ISSUE THREAD

**Issue by junjun-zhang** [icgc-argo/argo-meta#2]
## Describe the bug
PCAWG mini BAM entries are included as WGS, should be excluded.

## Steps To Reproduce
Here is one [example](https://github.com/icgc-argo/argo-meta/blob/7139e8154b84aade26fcbbf6e7d9b999aba14b7f/icgc_song_payloads/PACA-CA/00927e0b-afb5-4d7b-bea0-a62258216ea7.json)

## Expected behaviour
No PCAWG mini BAM should be included. Basically any of [these files](https://icgc.org/4oQ) should not be included.

**Comment by hknahal** [comment]
mini-BAM files have been excluded
