### ISSUE TITLE
Prepare SONG payloads from PCAWG WGS data from PACA-AU

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-meta#21]
Prepare SONG payloads for donors highlighted in green in `WGS` sheet: https://drive.google.com/file/d/11K6Zukx0mf1ChTsjvYXO3hYFZFXYfpmE/view?usp=sharing

**Comment by hknahal** [comment]
Summary of PCAWG WGS data currently in Collab: https://github.com/icgc-argo/argo-meta/blob/master/icgc_song_payloads/PACA-AU/batch1-PCAWG_PACA-AU_WGS_summary.tsv

SONG payloads: https://github.com/icgc-argo/argo-meta/tree/master/icgc_song_payloads/PACA-AU/batch1-pcawg

Waiting for confirmation from Amber. She indicated most likely they want this data to be imported to ARGO, but is checking with the PACA-AU team to confirm. Once confirmed, we can move forward with importing these payloads to intermediate-song.

**Comment by rosibaj** [comment]
Updated Jan 15- 2020 
When ready, @andricDu will complete the import.
Instructions are found here: https://wiki.oicr.on.ca/pages/viewpage.action?spaceKey=icgcargotech&title=Importing+Legacy+ICGC+objects+into+Intermediate-Song

**Comment by hknahal** [comment]
@rosibaj This batch of data is ready for import to intermediate-song now too: https://github.com/icgc-argo/argo-meta/tree/master/icgc_song_payloads/APGI-AU/WGS/batch1-pcawg I will update the ticket https://github.com/icgc-argo/roadmap/issues/706 to include this as well.

**Comment by rosibaj** [comment]
@hknahal is this batch of data still waiting to be imported?

**Comment by hknahal** [comment]
@rosibaj It was been imported already so I will close this ticket.
