### ISSUE TITLE
Prepare SONG payloads for PACA-AU non-PCAWG WGS data

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-meta#25]
Prepare SONG payloads for recently EGA->Collab transferred data (https://github.com/icgc-argo/ega-file-transfer/blob/master/ega_xml/v20201218/PACA-AU/PACA-AU_WGS_Audit_ICGC28.tsv). This dataset consists of **20 donors with non-PCAWG whole genome data** in Collaboratory (see data in Portal [here](https://dcc.icgc.org/repositories?files=%7B%22from%22:1,%22size%22:25%7D&filters=%7B%22file%22:%7B%22donorId%22:%7B%22is%22:%5B%22ES:f5b03ae0-045a-4704-898e-4e83408bfc8c%22%5D%7D%7D%7D)). These donors were confirmed by Amber from the PACA-AU project to have the additional core ARGO clinical data required (see "WGS donors missing in Collab" sheet in this [GoogleDoc table](https://drive.google.com/file/d/11K6Zukx0mf1ChTsjvYXO3hYFZFXYfpmE/view?usp=sharing)) Once the payloads are generated, they can imported into intermediate-song.

**Comment by hknahal** [comment]
SONG payloads generated: https://github.com/icgc-argo/argo-meta/tree/master/icgc_song_payloads/APGI-AU/WGS/batch2-non-pcawg

**Comment by hknahal** [comment]
Two SONG payloads belonging to submitterDonorId `ICGC_0235` were removed from this batch (https://github.com/icgc-argo/argo-meta/tree/master/icgc_song_payloads/APGI-AU/WGS/batch2-not-imported) because this donor is actually a PCAWG donor. However, it's PCAWG files are missing in Collaboratory and only exist in the `EGA-Hinxton` repository (see **[here](https://dcc.icgc.org/repositories?filters=%7B%22file%22:%7B%22donorId%22:%7B%22is%22:%5B%22ES:8ccc1245-a60f-476e-89a9-5e1e08b1be2e%22%5D%7D,%22donorStudy%22:%7B%22is%22:%5B%22PCAWG%22%5D%7D%7D%7D&files=%7B%22from%22:1,%22size%22:25%7D)**). The existing files in Collab (see **[here](https://dcc.icgc.org/repositories?filters=%7B%22file%22:%7B%22donorId%22:%7B%22is%22:%5B%22ES:8ccc1245-a60f-476e-89a9-5e1e08b1be2e%22%5D%7D,%22donorStudy%22:%7B%22is%22:%5B%22PCAWG%22%5D%7D,%22repoName%22:%7B%22is%22:%5B%22Collaboratory%20-%20Toronto%22%5D%7D%7D%7D&files=%7B%22from%22:1,%22size%22:25%7D)**) are actually recently transferred _non-PCAWG files_ from EGA -> Collab. The reason this donor's data at EGA was transferred to Collab was  because an audit revealed donor ID `ICGC_0235` was initially missing from Collaboratory. Question is why aren't this PCAWG donor's files showing in Collaboratory? (I'll create a separate ticket for this after I investigate this a bit more).

**Comment by hknahal** [comment]
@joneubank The following SONG payloads are ready to be imported to intermediate-song: https://github.com/icgc-argo/argo-meta/tree/master/icgc_song_payloads/APGI-AU/WGS/batch2-non-pcawg The ARGO project code is `APGI-AU`

**Comment by rosibaj** [comment]
@hknahal Are these payloads still waiting to be imported?

**Comment by hknahal** [comment]
@rosibaj They have been imported already so I will close this ticket.
