### ISSUE TITLE
Prepare sequencing_experiment SONG payloads for PACA-AU WXS data (46 donors)

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-meta#29]
Prepare SONG payloads for recently EGA->Collab transferred data (https://github.com/icgc-argo/ega-file-transfer/blob/master/ega_xml/v20201218/PACA-AU/PACA-AU_WXS_Audit_ICGC28.tsv). This dataset consists of 46 donors with whole exome data in Collaboratory (see data in Portal [here](https://dcc.icgc.org/repositories?filters=%7B%22file%22:%7B%22repoName%22:%7B%22is%22:%5B%22Collaboratory%20-%20Toronto%22%5D%7D,%22projectCode%22:%7B%22is%22:%5B%22PACA-AU%22%5D%7D,%22experimentalStrategy%22:%7B%22is%22:%5B%22WXS%22%5D%7D%7D%7D&files=%7B%22from%22:1,%22size%22:25%7D)). These donors were confirmed by Amber from the PACA-AU project to have the additional core ARGO clinical data required (see "WXS" tab in this GoogleDoc [table](https://docs.google.com/spreadsheets/d/11K6Zukx0mf1ChTsjvYXO3hYFZFXYfpmE/edit#gid=712988903)) Once the payloads are generated, they can imported into intermediate-song.

**Comment by hknahal** [comment]
SONG payloads prepared for 45 whole exome donors:https://github.com/icgc-argo/argo-meta/tree/batch3_paca-au_wxs/icgc_song_payloads/APGI-AU/WXS/batch3-wxs

1 donor (submitter_donor_id ICGC_0021 is excluded (https://github.com/icgc-argo/argo-meta/tree/batch3_paca-au_wxs/icgc_song_payloads/APGI-AU/WXS/batch3-not-imported) because the normal pair was not indicated by project (they only indicated the tumour sample). We will import this donor once we have a complete tumour/normal pair.

**Comment by rosibaj** [comment]
@hknahal are these still waiting to be imported?

**Comment by hknahal** [comment]
@rosibaj It was been imported already so I will close this ticket.
